name: Deploy to Sakura VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create env file
      run: |
        echo "NEXT_PUBLIC_API_BASE_URL=$API_BASE_URL" > .env.production

    - name: Install dependencies
      run: npm ci

    - name: Build static site
      run: npm run build

    - name: Deploy with rsync (manual)
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" out/ $VPS_USER@$VPS_HOST:/home/$VPS_USER/www/
      env:
        SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
